// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheConsortiumApp.Data;

#nullable disable

namespace TheConsortiumApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheConsortiumApp.Models.ComprobantePago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoAlquiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchivoExpensas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadFuncionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadFuncionalId");

                    b.ToTable("ComprobantesPagos");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.Consorcio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDepartamentos")
                        .HasColumnType("int");

                    b.Property<string>("CreadoPorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Consorcios");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ConsorcioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.LiquidacionExpensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsorcioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalGastos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId");

                    b.ToTable("LiquidacionesExpensa");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.LiquidacionExpensaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Coeficiente")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("LiquidacionExpensaId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoCalculado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadFuncionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionExpensaId");

                    b.HasIndex("UnidadFuncionalId");

                    b.ToTable("LiquidacionesExpensaDetalle");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.UnidadFuncional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ambientes")
                        .HasColumnType("int");

                    b.Property<string>("ArchivoContrato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Coeficiente")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("ConsorcioId")
                        .HasColumnType("int");

                    b.Property<bool>("EstaAlquilada")
                        .HasColumnType("bit");

                    b.Property<string>("NombreInquilino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePropietario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NroUnidad")
                        .HasColumnType("int");

                    b.Property<string>("PisoDepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId");

                    b.ToTable("UnidadesFuncionales");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.ComprobantePago", b =>
                {
                    b.HasOne("TheConsortiumApp.Models.UnidadFuncional", "UnidadFuncional")
                        .WithMany("ComprobantesPagos")
                        .HasForeignKey("UnidadFuncionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadFuncional");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.Consorcio", b =>
                {
                    b.HasOne("TheConsortiumApp.Models.Empresa", "Empresa")
                        .WithMany("Consorcios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheConsortiumApp.Models.Usuario", null)
                        .WithMany("Consorcios")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.Gasto", b =>
                {
                    b.HasOne("TheConsortiumApp.Models.Consorcio", "Consorcio")
                        .WithMany("Gastos")
                        .HasForeignKey("ConsorcioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheConsortiumApp.Models.Usuario", "Usuario")
                        .WithMany("Gastos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Consorcio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.LiquidacionExpensa", b =>
                {
                    b.HasOne("TheConsortiumApp.Models.Consorcio", "Consorcio")
                        .WithMany()
                        .HasForeignKey("ConsorcioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consorcio");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.LiquidacionExpensaDetalle", b =>
                {
                    b.HasOne("TheConsortiumApp.Models.LiquidacionExpensa", "Liquidacion")
                        .WithMany("Detalles")
                        .HasForeignKey("LiquidacionExpensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheConsortiumApp.Models.UnidadFuncional", "UnidadFuncional")
                        .WithMany()
                        .HasForeignKey("UnidadFuncionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Liquidacion");

                    b.Navigation("UnidadFuncional");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.UnidadFuncional", b =>
                {
                    b.HasOne("TheConsortiumApp.Models.Consorcio", "Consorcio")
                        .WithMany("UnidadesFuncionales")
                        .HasForeignKey("ConsorcioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consorcio");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.Usuario", b =>
                {
                    b.HasOne("TheConsortiumApp.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.Consorcio", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("UnidadesFuncionales");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.Empresa", b =>
                {
                    b.Navigation("Consorcios");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.LiquidacionExpensa", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.UnidadFuncional", b =>
                {
                    b.Navigation("ComprobantesPagos");
                });

            modelBuilder.Entity("TheConsortiumApp.Models.Usuario", b =>
                {
                    b.Navigation("Consorcios");

                    b.Navigation("Gastos");
                });
#pragma warning restore 612, 618
        }
    }
}
